apiVersion: batch/v1
kind: Job
metadata:
  name: simple-job
spec:
  template:
    metadata:
      name: simple-job
    spec:
      containers:
      - name: counter
        image: web
        imagePullPolicy: Never
        command:
         - "/bin/sh"
         - "-c"
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never