apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    mylabel: my-pod
spec:
  containers:
  - name: web
    image: web
    imagePullPolicy: Never
    ports:
    - containerPort: 1234
    livenessProbe:
      initialDelaySeconds: 2
      periodSeconds: 5
      httpGet:
        path: /
        port: 1234