
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

########################################################################################################################
# Metadata modifications
# Metadata changes that will be applied to all affected resources
########################################################################################################################
namespace: prod-namespace
namePrefix: prod-
commonLabels:
  prod-label: prod-val
  foo: prod-overwritten
commonAnnotations:
  prod-annotation: prod-annotation-val

########################################################################################################################
# Patches
# Small changes to existing resources
########################################################################################################################

patchesStrategicMerge:
- patch-pod-memory-limit-prod.yaml