
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

########################################################################################################################
# Metadata modifications
# Metadata changes that will be applied to all affected resources
########################################################################################################################
namespace: prod-namespace
namePrefix: dev-
commonLabels:
  prod-label: dev-val
  foo: dev-overwritten
commonAnnotations:
  dev-annotation: dev-annotation-val

########################################################################################################################
# Patches
# Small changes to existing resources
########################################################################################################################

patchesStrategicMerge:
- patch-pod-memory-limit-dev.yaml