apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-traefik-ingress
  labels:
    app: my-app
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: mytraefik.localhost
    http:
      paths:
      - path: /
        backend:
          serviceName: my-app
          servicePort: 8080