apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    mylabel: pod1
spec:
  containers:
  - name: web-pod1
    image: web
    imagePullPolicy: Never
    ports:
    - containerPort: 1234
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    mylabel: pod2
spec:
  containers:
  - name: web-pod2
    image: web
    imagePullPolicy: Never
    ports:
    - containerPort: 1234