---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mystatefulset
spec:
  selector:
    matchLabels:
      app: myapp
  serviceName: "mehdb"
  replicas: 2
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: container1
          image: web
          imagePullPolicy: Never
          ports:
            - containerPort: 1234
          volumeMounts:
            - name: data
              mountPath: /mydata
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mystatefulservice
  labels:
    app: myapp
spec:
  ports:
  - port: 9876
  clusterIP: None
  selector:
    app: myapp