# For minikube, constraints apply:
# https://github.com/kubernetes/minikube/blob/master/docs/persistent_volumes.md
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001
spec:
  storageClassName: my-storage-class # You can just make this up, it's just a way to map PVCs to PVs.
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath: # hostPath pv type needed for minikube
    path: /data/pv0001/