apiVersion: v1
kind: Service
metadata:
  name: another-service
spec:
  ports:
  - port: 4322
    protocol: TCP
    targetPort: 1234
  selector: # Selector determines which resource this service applies to
    mylabel: web-from-file-complex
  type: NodePort