
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Resources to act on
resources:
- my-pod.yaml

########################################################################################################################
# Metadata modifications
# Metadata changes that will be applied to all affected resources
########################################################################################################################
namespace: my-namespace
namePrefix: myprefix-
nameSuffix: -mysuffix
commonLabels:
  foo: bar
  hur: dur
commonAnnotations:
  my-annotation: my-annotation-value

########################################################################################################################
# Generators
# Generating new resources (currently only secrets and configmap)
# Note that you'd typically just use external .yaml files that declare the resource type.
# Joris: Note entirely sure why configmap and secrets need generators instead...
########################################################################################################################
generatorOptions:
  labels: # labels to add to all generated resources
    kustomize.generated.resources: kustomization-label
  annotations: # annotations to add to all generated resources
    kustomize.generated.resource: kustomization-annotation
  disableNameSuffixHash: true

configMapGenerator:
- name: my-java-server-env-vars
  literals:
  - JAVA_HOME=/opt/java/jdk
  - JAVA_TOOL_OPTIONS=-agentlib:hprof

secretGenerator:
- name: mysecret
  literals:
  - mysecret=42

########################################################################################################################
# Patches
# Small changes to existing resources
########################################################################################################################

patchesStrategicMerge:
- patch-pod-memory-limit.yaml